### ISSUE TITLE
.JsonMappingException: Numeric value (1712773960051) out of range of int (-2147483648 - 2147483647)

### ISSUE THREAD

**Issue by lbkulinski** [rainbowdashlabs/universalis-java#82]
Hello

I am making the following request:
```
MarketBoardResponse response;

try {
    response = this.universalisClient.marketBoard()
                                     .region(region)
                                     .itemsIds(id)
                                     .highQuality()
                                     .noGst()
                                     .queue()
                                     .get();
} catch (InterruptedException | ExecutionException e) {
    throw new RuntimeException(e);
}
```

This is causing the following exception to occur:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (1712773960051) out of range of int (-2147483648 - 2147483647)
 at [Source: (StringReader); line: 1, column: 77359] (through reference chain: de.chojo.universalis.entities.views.CurrentlyShownView["worldUploadTimes"])
```

I assume there is some issue in the type of the model? The URL of the request is `https://universalis.app/api/v2/North-America/36208?hq=true&noGst=true`

Thanks,
Logan

**Comment by rainbowdashlabs** [comment]
There was actually another issue. the time is provided in epoch millis while it got parsed in epoch seconds.
I will release that change in the next hours c:

Also noGst was actually removed. Tax is not exposed via a dedicated tax field in the Listing object.
If you want to directly get the result in blocking fashion you can use complete instead of queue().get() btw
